const destinations = [

    // Hill Station
    { name: "Manali", video: "videos/manali.mp4", category: "Hill Station" },
    { name: "Himachal", video: "videos/himachal.mp4", category: "Hill Station" },
    { name: "Munnar", video: "videos/munnar.mp4", category: "Hill Station" },
    { name: "Darjeeling", video: "videos/darjeeling.mp4", category: "Hill Station" },
    { name: "Dharamshala", video: "videos/dharamshala.mp4", category: "Hill Station" },
    { name: "Gangtok", video: "videos/gangtok.mp4", category: "Hill Station" },
    { name: "Mussoorie", video: "videos/mussoorie.mp4", category: "Hill Station" },
    { name: "Nainital", video: "videos/nainital.mp4", category: "Hill Station" },
    { name: "Ooty", video: "videos/ooty.mp4", category: "Hill Station" },
    { name: "Shimla", video: "videos/shimla.mp4", category: "Hill Station" },
    { name: "Dalhousie", video: "videos/dalhousie.mp4", category: "Hill Station" },
    { name: "Dehradun", video: "videos/dehradun.mp4", category: "Hill Station" },
    { name: "Kasol", video: "videos/kasol.mp4", category: "Hill Station" },
    { name: "Khandala", video: "videos/khandala.mp4", category: "Hill Station" },
    { name: "Lonavala", video: "videos/lonavala.mp4", category: "Hill Station" },
    { name: "Mahabaleshwar", video: "videos/mahabaleshwar.mp4", category: "Hill Station" },
    { name: "Ranikhet", video: "videos/ranikhet.mp4", category: "Hill Station" },
    { name: "Coorg", video: "videos/coorg.mp4", category: "Hill Station" },

    // Beach
    { name: "Goa", video: "videos/goa.mp4", category: "Beach" },
    { name: "Gokarna", video: "videos/gokarna.mp4", category: "Beach" },
    { name: "Pondicherry", video: "videos/pondicherry.mp4", category: "Beach" },
    { name: "Andaman", video: "videos/andaman.mp4", category: "Beach" },
    { name: "Kerala", video: "videos/kerala.mp4", category: "Beach" },
    { name: "Wayanad", video: "videos/wayanad.mp4", category: "Beach" },

    // Snow
    { name: "Kashmir", video: "videos/kashmir.mp4", category: "Snow" },
    { name: "Ladakh", video: "videos/ladakh.mp4", category: "Snow" },
    { name: "Gulmarg", video: "videos/gulmarg.mp4", category: "Snow" },
    { name: "Auli", video: "videos/auli.mp4", category: "Snow" },
    { name: "Valley of Flowers", video: "videos/valleyofflowers.mp4", category: "Snow" },
        // Spiritual
    { name: "Varanasi", video: "videos/varanasi.mp4", category: "Spiritual" },
    { name: "Amritsar", video: "videos/amritsar.sp.mp4", category: "Spiritual" },
    { name: "Badrinath", video: "videos/badrinath.sp.mp4", category: "Spiritual" },
    { name: "Haridwar", video: "videos/haridwar.sp.mp4", category: "Spiritual" },
    { name: "Kedarnath", video: "videos/kedarnath.mp4", category: "Spiritual" },
    { name: "Rishikesh", video: "videos/rishikesh.mp4", category: "Spiritual" },
    { name: "Tirupati", video: "videos/tirupati.mp4", category: "Spiritual" },
    { name: "Ajmer", video: "videos/ajmer.mp4", category: "Spiritual" },
    { name: "Dwarka", video: "videos/dwarka.mp4", category: "Spiritual" },
    { name: "Somnath", video: "videos/somnath.mp4", category: "Spiritual" },
    { name: "Vrindavan", video: "videos/vrindavan.mp4", category: "Spiritual" },
    { name: "Banaras", video: "videos/banaras.mp4", category: "Spiritual" },

    // Historical
    { name: "Rajasthan", video: "videos/rajasthan.mp4", category: "Historical" },
    { name: "Agra", video: "videos/agra.hist.mp4", category: "Historical" },
    { name: "Ellora", video: "videos/ellora.mp4", category: "Historical" },
    { name: "Hampi", video: "videos/hampi.mp4", category: "Historical" },
    { name: "Jaipur", video: "videos/jaipur.mp4", category: "Historical" },
    { name: "Udaipur", video: "videos/udaipur.mp4", category: "Historical" },
    { name: "Jaisalmer", video: "videos/jaisalmer.mp4", category: "Historical" },
    { name: "Jodhpur", video: "videos/jodhpur.mp4", category: "Historical" },
    { name: "Bikaner", video: "videos/bikaner.mp4", category: "Historical" },
    { name: "Mount Abu", video: "videos/mountabu.mp4", category: "Historical" },
    { name: "Pushkar", video: "videos/pushkar.mp4", category: "Historical" },
    { name: "Tamil Nadu", video: "videos/tamilnadu.mp4", category: "Historical" },
        // Spiritual
    { name: "Varanasi", video: "videos/varanasi.mp4", category: "Spiritual" },
    { name: "Amritsar", video: "videos/amritsar.sp.mp4", category: "Spiritual" },
    { name: "Badrinath", video: "videos/badrinath.sp.mp4", category: "Spiritual" },
    { name: "Haridwar", video: "videos/haridwar.sp.mp4", category: "Spiritual" },
    { name: "Kedarnath", video: "videos/kedarnath.mp4", category: "Spiritual" },
    { name: "Rishikesh", video: "videos/rishikesh.mp4", category: "Spiritual" },
    { name: "Tirupati", video: "videos/tirupati.mp4", category: "Spiritual" },
    { name: "Ajmer", video: "videos/ajmer.mp4", category: "Spiritual" },
    { name: "Dwarka", video: "videos/dwarka.mp4", category: "Spiritual" },
    { name: "Somnath", video: "videos/somnath.mp4", category: "Spiritual" },
    { name: "Vrindavan", video: "videos/vrindavan.mp4", category: "Spiritual" },
    { name: "Banaras", video: "videos/banaras.mp4", category: "Spiritual" },

    // Historical
    { name: "Rajasthan", video: "videos/rajasthan.mp4", category: "Historical" },
    { name: "Agra", video: "videos/agra.hist.mp4", category: "Historical" },
    { name: "Ellora", video: "videos/ellora.mp4", category: "Historical" },
    { name: "Hampi", video: "videos/hampi.mp4", category: "Historical" },
    { name: "Jaipur", video: "videos/jaipur.mp4", category: "Historical" },
    { name: "Udaipur", video: "videos/udaipur.mp4", category: "Historical" },
    { name: "Jaisalmer", video: "videos/jaisalmer.mp4", category: "Historical" },
    { name: "Jodhpur", video: "videos/jodhpur.mp4", category: "Historical" },
    { name: "Bikaner", video: "videos/bikaner.mp4", category: "Historical" },
    { name: "Mount Abu", video: "videos/mountabu.mp4", category: "Historical" },
    { name: "Pushkar", video: "videos/pushkar.mp4", category: "Historical" },
    { name: "Tamil Nadu", video: "videos/tamilnadu.mp4", category: "Historical" },
        // City
    { name: "Delhi", video: "videos/delhi.mp4", category: "City" },
    { name: "Mumbai", video: "videos/mumbai.mp4", category: "City" },
    { name: "Ahmedabad", video: "videos/ahmedabad.city.mp4", category: "City" },
    { name: "Bangalore", video: "videos/bangalore.city.mp4", category: "City" },
    { name: "Chennai", video: "videos/chennai.city.mp4", category: "City" },
    { name: "Hyderabad", video: "videos/hyderabad.city.mp4", category: "City" },
    { name: "Kolkata", video: "videos/kolkata.mp4", category: "City" },
    { name: "Prayagraj", video: "videos/prayagraj.mp4", category: "City" },
    { name: "Pune", video: "videos/pune.city.mp4", category: "City" },
    { name: "Chandigarh", video: "videos/chandigarh.mp4", category: "City" },
    { name: "Lucknow", video: "videos/lucknow.mp4", category: "City" },

    // Adventure
    { name: "Meghalaya", video: "videos/meghalaya.mp4", category: "Adventure" },
    { name: "Shillong", video: "videos/shillong.mp4", category: "Adventure" },
    { name: "Spiti Valley", video: "videos/spitivalley.mp4", category: "Adventure" },
    { name: "Saputara", video: "videos/saputara.mp4", category: "Adventure" },
    { name: "Nashik", video: "videos/nashik.mp4", category: "Adventure" },

];